# Generated by Django 4.2.29 on 2026-03-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_name', models.CharField(blank=True, max_length=100)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('professional', 'Professional'), ('expert', 'Expert')], default='friendly', max_length=50)),
                ('goal', models.TextField(default='Collect name and phone number for a manager callback')),
                ('greeting_template', models.TextField(blank=True)),
                ('escalation_trigger', models.TextField(blank=True)),
                ('forbidden_topics', models.TextField(blank=True)),
                ('additional_instructions', models.TextField(blank=True)),
            ],
        ),
    ]
