# Generated by Django 4.2.29 on 2026-03-05 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_user_id', models.CharField(max_length=100)),
                ('instagram_username', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('active', 'Active'), ('qualified', 'Qualified'), ('lead', 'Lead'), ('handed_off', 'Handed Off'), ('closed', 'Closed')], default='new', max_length=20)),
                ('is_bot_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('comment', 'Comment'), ('dm', 'Direct Message')], max_length=20)),
                ('source_post_id', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogs', to='accounts.instagramaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('manager', 'Manager')], max_length=10)),
                ('text', models.TextField()),
                ('instagram_message_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dialogs.dialog')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
