# Generated by Django 4.2.29 on 2026-03-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('source_type__gt', '')), fields=('tenant', 'source_type', 'source_id'), name='unique_external_source'),
        ),
    ]
