# Generated by Django 4.2.29 on 2026-03-05 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCRMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_url', models.URLField()),
                ('auth_type', models.CharField(choices=[('bearer', 'Bearer Token'), ('header', 'Custom Header'), ('query', 'Query Parameter')], default='bearer', max_length=20)),
                ('auth_key', models.CharField(default='Authorization', max_length=100)),
                ('auth_value', models.TextField()),
                ('items_path', models.CharField(default='results', help_text='Dot-separated path to items array in API response, e.g. "data.services"', max_length=200)),
                ('field_id', models.CharField(default='id', max_length=100)),
                ('field_name', models.CharField(default='name', max_length=100)),
                ('context_template', models.TextField(help_text='Template with {{ field }} placeholders to build item context')),
                ('sync_interval_minutes', models.IntegerField(default=60)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_configs', to='tenants.tenant')),
            ],
        ),
    ]
